-- Script SQL pour créer la table produits et insérer les données
-- À exécuter dans l'interface Supabase (SQL Editor)

-- 1. Création de la table produits
CREATE TABLE IF NOT EXISTS produits (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nom TEXT NOT NULL,
  prix NUMERIC NOT NULL,
  description TEXT NOT NULL,
  stock INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Insertion des produits
INSERT INTO produits (nom, prix, description, stock) VALUES
  ('Savon Purifiant à l''Huile de Nigelle', 15.000, 'Savon artisanal purifiant pour peaux grasses', 50),
  ('Crème Apaisante à l''Aloe Vera', 22.000, 'Crème hydratante et apaisante pour le visage', 30),
  ('Savon Exfoliant au Marc de Café', 12.000, 'Savon exfoliant naturel pour une peau douce', 40),
  ('Huile de Graines de Figue de Barbarie', 45.000, 'Huile précieuse anti-âge bio', 25)
ON CONFLICT DO NOTHING;

-- 3. Activer Row Level Security (RLS)
ALTER TABLE produits ENABLE ROW LEVEL SECURITY;

-- 4. Créer une policy pour permettre la lecture publique (role anon)
CREATE POLICY "Permettre la lecture publique des produits"
  ON produits
  FOR SELECT
  TO anon, authenticated
  USING (true);

-- 5. (Optionnel) Policy pour l'écriture (si nécessaire pour l'admin)
CREATE POLICY "Permettre l'écriture aux administrateurs"
  ON produits
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
